### ISSUE TITLE
Show more information on page.

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/randomvm#23]
I went to go a meeting tonight, and the password information did not display as it was in the comments section.

![image](https://user-images.githubusercontent.com/1850811/144944029-721c935c-4d7e-4c44-8cc0-fdebed8338d5.png)

![image](https://user-images.githubusercontent.com/1850811/144944004-d5eb6df9-14ce-4758-b622-535586a0cc6b.png)

**Comment by jbraswell** [comment]
Implemented

**Comment by dgershman** [comment]
👍
